Feat/issue 515
h2oai/wave pull request #1207
Opened 2022-01-25 13:53 UTC by marek-mihok

Adds optional `overflow` property to `ui.table_column` which defines how to handle the long text that does not fit into the cell. 

Possible values are:

- `tooltip`
_Shows a tooltip in case text does not fit into the cell_

https://user-images.githubusercontent.com/23740173/150987809-f6066045-58f5-465c-8739-417ea0f2b254.mov

- `wrap`
_Wraps text into multiple lines in case text does not fit into the cell_

![image](https://user-images.githubusercontent.com/23740173/150988025-4087caa1-1179-4180-97a0-7f2047cefb1e.png)

Closes #515

2022-02-02 09:16 UTC, mturoci requested changes
Thanks @marek-mihok. Please also add a docs section about the table row overflow. Use `wrap` as an example there since there is currently no way to simulate hover during screenshot creation.

2022-02-02 09:16 UTC, mturoci commented on ui/src/table.tsx
> +          if (col.overflow === 'wrap') return <span style={{ whiteSpace: col.overflow === 'wrap' ? 'normal' : undefined }}>{children}</span>
We already know that overflow === 'wrap' so:
```suggestion
          if (col.overflow === 'wrap') return <span style={{ whiteSpace: 'normal' }}>{children}</span>
```

2022-02-18 11:05 UTC, mturoci submitted a review, later dismissed
Thanks, @marek-mihok! LGTM.

@lo5 could you have a quick look at the proposed API, please?

```ts
 /** Defines how to handle the long text that does not fit into the cell. */
overflow?: 'tooltip' | 'wrap'
```

2022-03-16 17:03 UTC, lo5 commented on ui/src/table.tsx
> +  /** Defines how to handle the long text that does not fit into the cell. */
```suggestion
  /** Defines what to do with a cell's contents in case it does not fit inside the cell. */
```

2022-03-16 17:03 UTC, lo5 commented on ui/src/table.tsx
> +  overflow?: 'tooltip' | 'wrap'
```suggestion
  cell_overflow?: 'tooltip' | 'wrap'
```

2022-03-16 17:05 UTC, lo5 commented
@marek-mihok - sorry, hit the approve button by mistake - needs changes.

2022-03-25 12:39 UTC, mturoci requested changes
Since there are no dependency changes in `package.json`, there should not be any changes in `package-lock.json` either. Remove the changes and the PR is good to go.

2022-03-25 13:43 UTC, merged