docs: blog - deploying wave apps on heroku
h2oai/wave pull request #1234
Opened 2022-02-05 08:12 UTC by srini-x

A blog post explaining how to deploy Wave apps on Heroku.

 In response to this Stack Overflow question
https://stackoverflow.com/questions/65836484/deploy-h2o-wave-application-to-heroku

2022-02-07 08:36 UTC, mturoci requested changes
Thanks @srini-x, the blog post looks great.

I would suggest simplifying the docker part though and cover only the simplest happy path (0..20+). The reason is, although correct, your proposed deployment is too complex. The primary consumers of this blog post will be people that have no idea how docker or linux in general works (if they did, they wouldn't need this in the first place) so we should give them something they are able to understand and quickly add into their apps. The simplest dockerfile I can think of is:

```dockerfile
# Get base image with python installed.
FROM python:3.8
# Copy over everything.
COPY . .
# Install needed dependencies.
RUN pip install -r requirements.txt
# Run the app.
CMD ["wave", "run", "--no-reload", "app.py"]
```

So the guide should be something like:

* Create such dockerfile
* Adjust your desired python version if necessary (3.8 should work fine)
* Make sure you have requirements.txt present
* Adjust your python module name in `CMD` (instead of app.py)
* Build it using docker build ...
* Verify it works using docker run ...

2022-02-07 23:10 UTC, srini-x commented
@mturoci I agree with you on the idea that the target audience is not very familiar with Docker or Linux. That is the reason I had to make this Dockerfile.

with this setup, users can use any version of Python or Wave any Python module name and they don't have to edit any files

steps are actually very simple

1. copy `Dockerfile`, `docker_entrypoint.sh`. we can even exclude `.dockerignore`
2. run 

```shell
$ docker build \
 --build-arg PYTHON_VERSION=3.8 \
 --build-arg WAVE_VERSION=0.20.0 \
 --build-arg PYTHON_MODULE="ai_app/app.py" \
 -t wave-heroku:0.1.0 .
```
3. Done

Also, the Dockerfile need to be a bit more complicated than what you suggested because `$PORT` is randomly selected by Heroku during the time of deployment.

so, we need to add `H2O_WAVE_ADDRESS="http://127.0.0.1:${PORT}"` and `-listen ":${PORT}"` flag to `waved`
I think we can use environment variable `H2O_WAVE_LISTEN` instead of the `-listen` flag.

Since `$PORT` is defined during runtime, we need the `docker-entrypoint.sh`.

2022-02-08 07:56 UTC, mturoci commented
> with this setup, users can use any version of Python or Wave any Python module name and they don't have to edit any files

Ye, I agree. My point is more about the understanding of the copy-pasted code. If it works for them, fine, but if it will require some additional minor tweaks, there is no chance they can make it work as it's too complex. People who are able to understand it don't need this blog anyway as they can write it up themselves.

I consider this blog post a "toy-deployment" for "toy-apps", which means for people who have minimal programming skills but still would like to showcase their app somehow. Real prod deployments probably won't be made by a data scientist.

> If you feel strongly that the Dockerfile need to be simplified, I can make a new simplified version that works with $PORT

Just wondering what would be the best option for our target audience. Let's also invite @lo5 and @mtanco to the discussion. You can leave it as it is until we make a final decision.

### Final note

It would be good to also add a link to HAC at the end. Something in the lines of - if you find this too complex/not so scalable, try out our HAC for enterprises which makes this whole process way easier etc.

2022-02-08 17:31 UTC, srini-x commented
@mturoci cool I agree with you.

2022-02-11 15:47 UTC, woobe commented
IMHO, readers may not want to read the detailed solution straightaway. For this blog post, I would recommend the following:

First, we can start with the problem statement (in this case, what are the challenges of deploying Wave apps).

After that, we can talk about a few possible solutions:
- Solution 1: Heroku, pros and cons, final outcomes (with a link to the full step-by-step instructions)
- Solution 2: Another solution, pros and cons, etc
- ...
- Solution x: Finally, the beauty of HAIC, final outcomes (with some cool screenshots showing how to import apps)

2022-04-01 19:15 UTC, lo5 requested changes
Thanks a ton for putting this together @srini-x!

Only minor changes - please accept if you're OK with them.

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +$ python -m venv .venv
```suggestion
$ python -m venv venv
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +$ . .venv/bin/activate
```suggestion
$ ./venv/bin/activate
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +The following is a walk through on how to deploy a Wave app on Heroku.
```suggestion
This blog post describes how you can deploy a Wave app on Heroku.
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +Following are the step by step instructions to deploy your [Wave][wave] app to [Heroku][heroku-home] platform. All the code for this blog post is also available in a [GitHub repository][wave-heroku-r
```suggestion
Here are step by step instructions to deploy your [Wave][wave] app to [Heroku][heroku-home] platform. All the code for this blog post is also available in a [GitHub repository][wave-heroku-repo].
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +If you are using Wave version older than `0.20.0`, you need to start the Wave server (`waved`) before running the
```suggestion
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +The app will be available at http://localhost:10101.
```suggestion
The app will be available at http://localhost:10101.


Note that if you are using a Wave version older than `0.20.0`, you'll need to first start the Wave server (`waved`) before running the Python app. Please refer to the [Wave Docs][wave-older-versions].
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +If you are following along from the top and cloned the example repo, the files are already there.
```suggestion
If you are following along from the top and have cloned the example repo, the files will already be there.
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +app will be available at http://localhost:10101
```suggestion
Your app can be accessed at http://localhost:10101
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +Ok. Hard part is over. Let's login to Heroku and deploy our app.
```suggestion
OK. The hard part is over. Let's login to Heroku and deploy our app.
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +Once we have Heroku CLI installed, we can login to Heroku using the following command.
```suggestion
Once we have the Heroku CLI installed, we can login to Heroku using the following command.
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +Be in the root of the repo and run.
```suggestion
Navigate to the root of the repo and run.
```

2022-04-01 19:15 UTC, lo5 commented on website/blog/2022-02-08-wave-on-heroku.md
> +## What is Next?
```suggestion
## What's next?
```

2022-07-11 08:11 UTC, mturoci commented
Closing as this has already been published [here](https://medium.com/@srini.x/deploy-your-wave-app-in-5-minutes-bd440d00917f?source=rss-2dbd7cf54686------2)

2022-07-11 08:11 UTC, closed without merging