Add closable prop into side panel
h2oai/wave pull request #1315
Opened 2022-03-30 12:46 UTC by marek-mihok

This PR introduces `closable` prop for side panel. It also updates API descriptions for `events` prop for both side panel and dialog. The updated APIs look as follows:

__Side panel:__

```ts
export interface SidePanel {
  /** The side panel's title. */
  title: S
  /** The components displayed in this side panel. */
  items: Component[]
  /** The width of the dialog, e.g. '400px'. Defaults to '600px'. */
  width?: S
  /** True if the side panel should have a closing 'X' button at the top right corner. */
  closable?: B
  /** An identifying name for this component. */
  name?: Id
  /** The events to capture on this side panel. One of 'dismissed'. */
  events?: S[]
  /** True to prevent closing when clicking or tapping outside the side panel. Prevents interacting with the page behind the side panel. Defaults to False. */
  blocking?: B
}
```

__Dialog:__
```ts
export interface Dialog {
  /** The dialog's title. */
  title: S
  /** The components displayed in this dialog. */
  items: Component[]
  /** The width of the dialog, e.g. '400px'. Defaults to '600px'. */
  width?: S
  /** True if the dialog should have a closing 'X' button at the top right corner. */
  closable?: B
  /** True to prevent closing when clicking or tapping outside the dialog. Prevents interacting with the page behind the dialog. Defaults to False. */
  blocking?: B
  /** Dialog with large header banner, mutually exclusive with `closable` prop. Defaults to False. */
  primary?: B
  /** An identifying name for this component. */
  name?: Id
  /** The events to capture on this dialog. One of 'dismissed'. */
  events?: S[]
}
```

It also brings updated docs to make dialog and side panel consistent with each other.

Closes #1161 
Closes #1294

2022-03-30 14:02 UTC, mturoci requested changes
Thanks @marek-mihok, a few minor comments.

2022-03-31 08:04 UTC, marek-mihok commented on ui/src/side_panel.tsx
> +      if ((closable || !blocking) && ev && name) wave.emit(name, ev, true)
You are right. I've changed this also for dialog and tested it.

2022-03-31 09:14 UTC, mturoci requested changes

2022-03-31 09:14 UTC, mturoci commented on ui/src/side_panel.tsx
> +  blocking?: B
Preserve the existing attributes order and place any new optional attributes at the end.

2022-03-31 09:57 UTC, mturoci approved these changes
Thanks @marek-mihok, looking good.

2022-03-31 09:59 UTC, merged