Modify return value for line plot event
h2oai/wave pull request #1332
Opened 2022-04-07 12:02 UTC by marek-mihok

This PR modifies the return value for line plot event to be left and right point of the clicked line segment instead of the whole line.

![image](https://user-images.githubusercontent.com/23740173/162194122-a750df76-7c5d-44cf-885c-a52af82c7c76.png)

Closes #1331

2022-04-13 09:00 UTC, mturoci requested changes
Thanks @marek-mihok.

Did you make sure this does not break the rest of existing plot types?

cc @lo5 since this is a breaking change

2022-04-13 09:00 UTC, mturoci commented on ui/src/plot.tsx
> +                      }) : data
```suggestion
                      dataInterval = shape === 'line' ? data.filter((item: any, idx: U) =>
                        (idx !== points.length - 1 && x >= points[idx].x && x <= points[idx + 1].x)
                        || (idx !== 0 && x <= points[idx].x && x >= points[idx - 1].x)
                      ) : data
```

2022-04-19 17:09 UTC, lo5 commented
The new behavior is odd. Line segments might make sense from a graphics perspective, but not from a data visualization perspective. I can't think of any common scenarios where the app author might need to deal with line segments. 

Clicking on a line has a very specific intent - selecting the *series*. e.g. On a multi-series line plot of, say, revenue over time by product, where each line represents a product, clicking on a line would mean "the user is interested in the product", which could be followed up with a, say, drill-down operation or such.

This behavior obviously would make no sense if there is a single line plot, which is why the plots support adding additional layers of marks for greater control over interactivity.

The problem here, as pointed out by @fousasg, is that if the plot only has a single line, clicking on a line doesn't make the user's intent clear. 

So the correct fix to this problem could be: introduce an `interactive: boolean` attribute on each mark, defaulting to `true`. If `interactive === false`, don't raise events for that mark layer. This way, the multi-series line plots are not affected, and if the author desires a single-line plot with interactivity, using a point layer on top of a line layer with the line layer set to `interactive=false` will solve the inadvertent-clicking problem.

What do you think?

2022-05-05 07:46 UTC, mturoci requested changes
Thanks @marek-mihok, looks good overall, just a few docs nitpicks.

2022-05-05 07:46 UTC, mturoci commented on website/widgets/plots/overview.md
> +If you do not wish to raise wave events on interaction with specific mark, simply specify it `interactive=False` attribute.
```suggestion
If you do not wish to raise wave events on interaction with a specific mark, simply specify the `interactive=False` attribute.
```

2022-05-05 07:46 UTC, mturoci commented on website/widgets/plots/overview.md
> +    plot=ui.plot([ui.mark(type='interval', x='=salary', y='=profession', y_min=0, interactive=False)])
Would be better to include the solution to a problem described in #1331.

2022-07-06 12:49 UTC, mturoci approved these changes
Good job @marek-mihok!

2022-07-06 12:49 UTC, merged