Image annotator
h2oai/wave pull request #1400
Opened 2022-05-04 13:04 UTC by mturoci

Closes #1323

2022-05-04 14:56 UTC, dott1718 commented
Thank you @mturoci, the component looks great! We will provide more feedback as soon as we can try it out.

2022-05-11 02:16 UTC, lo5 commented
Demo looks great :guitar:!

It's not clear to me how `items` and `ImageAnnotatorItem`, `ImageAnnotatorShape`, `ImageAnnotatorRect` are intended to be used. The one example in this PR doesn't use any of them. Maybe that'll help clarify why `tag` is a string, and why `rect` is an attribute of `~Shape`. It would be good to add another example that show those components in use.

2022-05-11 07:29 UTC, mturoci commented
> It's not clear to me how items and ImageAnnotatorItem, ImageAnnotatorShape, ImageAnnotatorRect are intended to be used.

I updated the existing example to show predefined annotation. The basic reasoning is:

* Tag is a string so that we are consistent with tag in `ui.text_annotator` + there are not many other options.
* The `ImageAnnotatorShape` is a bit more tricky, but the overarching goal is to do us a favor and allow for extending the image annotator with other shapes in the future, e.g. circle/paths. I took this approach to be consistent with how we define our table cell types.

2022-05-11 13:08 UTC, mturoci commented
@lo5 one more thing that is worth discussing is the image aspect ratio. Since images to be annotated can be various sizes, we have basically 2 options:

* Display them in their original (intrinsic) size even at the price of scrollbars (in case of overflow).
* Provide `height` attr and scale the image accordingly - I went for this option.

Since I chose the second option as it is more UX-friendly, I had to make adjustments to the coordinates based on the aspect ratio so that developers can specify and receive coordinates relative to the original size of their img. Example:

Original img: 100x100 with coordinates 10,10.
Scaled image with height 50px: 50x50 with coordinates translated to 5,5.

The proposed approach makes sense to me, but feel free to point out any alternatives as you see fit.

2022-05-11 15:47 UTC, lo5 commented
OK, so if I'm understanding this correctly, `ImageAnnotatorItem.tag` looks up an *existing* `ImageAnnotatorTag.name` to determine the label and color?

2022-05-11 15:56 UTC, mturoci commented
>OK, so if I'm understanding this correctly, ImageAnnotatorItem.tag looks up an existing ImageAnnotatorTag.name to determine the label and color?

That's right.

2022-05-12 02:52 UTC, lo5 requested changes

2022-05-12 02:52 UTC, lo5 commented on ui/src/image_annotator.tsx
> +  /** Tag connected to the highlighted section. */
```suggestion
  /** The `name` of the image annotator tag to refer to for the `label` and `color` of this item. */
```

(Also change the docstring for the text annotator item if possible).

2022-05-12 02:52 UTC, lo5 commented on ui/src/image_annotator.tsx
> +  /** HEX or RGB color string used as background for highlighted phrases. */
```suggestion
  /** Hex or RGB color string to be used as the background color. */
```

2022-05-12 02:52 UTC, lo5 commented on ui/src/image_annotator.tsx
> +  /** Text to be displayed. */
```suggestion
  /** Text to be displayed for the annotation. */
```

2022-05-12 02:52 UTC, lo5 commented on ui/src/image_annotator.tsx
> + * The image annotator component enables user to manually annotate parts of an image.
```suggestion
 * This component allows annotating and labeling parts of an image by drawing shapes with a pointing device.
```

2022-05-12 02:52 UTC, lo5 commented on ui/src/image_annotator.tsx
> +  /** The text annotator's title. */
```suggestion
  /** The image annotator's title. */
```

2022-05-12 06:59 UTC, mturoci commented on ui/src/image_annotator.tsx
> +  /** The card’s image height. Intrinsic image size is used by default. */
Intrinsic means actual (real) image size.

2022-05-12 13:20 UTC, mturoci commented on ui/src/image_annotator.tsx
> +  /** The card’s image height. Intrinsic image size is used by default. */
Changed to `The card’s image height. The actual image size is used by default`.

2022-05-12 13:44 UTC, mturoci commented on py/examples/image_annotator.py
> +                        shape=ui.image_annotator_shape(rect=ui.image_annotator_rect(x1=649, y1=393, x2=383, y2=25)),
Much better now.

2022-05-17 13:27 UTC, merged