fix: Add icon to masked textfield component #1536
h2oai/wave pull request #1539
Opened 2022-07-13 11:56 UTC by aalencar

closes #1536

2022-07-13 13:39 UTC, mturoci reviewed
Thanks @aalencar. Seems like there are more missing props though. Let's create a single `Fluent.ITextFieldProps` that will be passed into both `MaskedTextField` and `TextField` to have this resolved once and for all.

2022-07-15 09:20 UTC, mturoci commented on ui/src/textbox.tsx
> +      textFieldProps: Fluent.ITextFieldProps = {
Can we also add `data-test` here?

2022-07-15 09:21 UTC, mturoci requested changes
Can we also include `data-test` within `textFieldProps`?

2022-07-15 14:18 UTC, aalencar commented
> Can we also include `data-test` within `textFieldProps`?

Let's use `textFieldProps` only for `Fluent.ITextFieldProps` properties.

2022-07-15 14:19 UTC, mturoci commented
>Let's use textFieldProps only for Fluent.ITextFieldProps properties.

Why?

2022-07-15 14:50 UTC, mturoci commented
That's fine. The goal here is to have a single source of truth for common props.

2022-07-18 07:20 UTC, mturoci approved these changes

2022-07-18 07:21 UTC, merged