feat: Allow skipping Wave server TLS verification #1547
h2oai/wave pull request #1556
Opened 2022-07-25 11:03 UTC by mturoci

Closes #1547

2022-08-02 17:01 UTC, lo5 requested changes
Thanks @mturoci - minor (refactoring) changes.

2022-08-02 17:01 UTC, lo5 commented on website/docs/configuration.md
> +Make sure the TLS verification is not turned off in production environments as it's a huge security hole.
```suggestion
**Disabling TLS verification is a security risk.** Make sure TLS is not disabled in production environments.
```

2022-08-03 06:53 UTC, mturoci commented on cmd/wave/main.go
> +	boolVar(&verifyTLS, "verify-tls", true, "do not verify TLS certificates during external communication - DO NOT USE IN PRODUCTION")
Agree, done.

2022-08-03 06:55 UTC, mturoci commented on cmd/wave/main.go
> +		verifyTLS            bool
Done.

2022-08-03 06:59 UTC, mturoci commented on cmd/wave/main.go
> +	if !verifyTLS {
Not necessarily. Skipping TLS verification can happen even if Wave itself is not using TLS certs. E.g. server is listening on HTTP, but wants to communicate with a Keycloak that is using a self-signed cert. Agree with colocating the TLS logic though, we should just not put it into the proposed if block IMO.

2022-08-08 08:20 UTC, merged