docs: added Github Star count button
h2oai/wave pull request #1620
Opened 2022-09-13 22:53 UTC by YashasviChaurasia

Added GitHub Star count below Get Started button on the website,
solves Issue#1619

Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>

2022-09-14 07:13 UTC, mturoci commented
Hi @YashasviChaurasia, if you want to work on some issue, please comment on it and wait for the confirmation of the Wave team member first. This one is already taken.

See [contribution guidelines](https://github.com/h2oai/wave/blob/master/.github/CONTRIBUTING.md) prior to contributing.

Moreover, your PR should be runnable without throwing any errors.

2022-09-14 07:49 UTC, YashasviChaurasia commented
Ok, sorry for the inconvenience caused.
Will look into it from next time.
Could you please specify the error for my understanding. 
Thank you

2022-09-14 10:25 UTC, mturoci commented
Np. The problem is that whenever you add a new npm package (in this case `react-github-btn`), you also need to commit the changed `package-lock.json` file so that whoever picks up your changes only needs to run `npm ci` and will get the exact dependencies as you did.

2022-09-28 06:07 UTC, mturoci requested changes
Thanks @YashasviChaurasia, in addition to missing `package-lock`, a bit of extra formatting is also needed.

2022-09-28 06:07 UTC, mturoci commented on website/src/pages/index.js
> +
Formatting:

* remove extra blank lines
* line is quite long, separate attributes with newlines

2022-09-28 07:33 UTC, mturoci requested changes
* When adding a new npm dependency, you need to commit both `package.json` and `package-lock.json` so after running `npm ci` to do the initial setup, you run `npm i <your-dep>` which edits both of the mentioned files which need to be commited.
* Please attach screenshots/gifs to the PR description so that we can see if the button is properly aligned and works as expected.
* add `Closes #<issue-number` clause to link the PR with the GH issue and automatically close it after merging.

Thanks!

2022-10-05 06:41 UTC, mturoci commented
Closing due to inactivity.

2022-10-05 06:41 UTC, closed without merging