feat: Add vertical alignment to ui.inline
h2oai/wave pull request #1640
Opened 2022-09-28 03:12 UTC by NevilleMthw

Hi, @mturoci, this resolves #1535. Please do check if what I have done is correct.

Thanks,
Neville

2022-09-28 05:57 UTC, mturoci commented
Thanks for the PR @NevilleMthw! Unfortunately, this is not what is needed to be done. I have updated the issue description, so please have a look. I also suggest going through contribution guidelines that describe what needs to be done when adding new props to cards/components.

2022-09-28 18:17 UTC, NevilleMthw commented
Oh okay. Thanks for the feedback. I will go through the issue again. @mturoci.

2022-10-03 10:17 UTC, mturoci requested changes
Thanks for the PR @NevilleMthw! Can you also please include python examples showcasing your feature + update PR description with the screenshots so that we can see how does the feature works in practice.

2022-10-05 01:58 UTC, NevilleMthw commented
> Thanks for the PR @NevilleMthw! Can you also please include python examples showcasing your feature + update PR description with the screenshots so that we can see how does the feature works in practice.

Hi, I will definitely look at trying to create a Python example. Will let you know. Thanks.

2022-10-19 10:39 UTC, mturoci commented
Closing due to inactivity.

2022-10-19 10:39 UTC, closed without merging