feat: Added label parameter to ui.menu
h2oai/wave pull request #1663
Opened 2022-10-08 00:34 UTC by Pooja444

## Github Issue

https://github.com/h2oai/wave/issues/1577

## Description

Added a 'label' parameter to the UI component of wave. This label will be displayed beside the arrow for the menu dropdown. It will also be clickable, i.e. the dropdown will open on clicking the arrow as well as the label.

## Successful local test - 

<img width="530" alt="Screen Shot 2022-10-07 at 5 24 37 PM" src="https://user-images.githubusercontent.com/24620969/194678543-f7aebe64-d76d-472b-bd43-cbc1d39ae594.png">

2022-10-10 05:34 UTC, mturoci requested changes
Looks great @Pooja444! A few minor changes. Also do not forget to run `make generate` after changing the docstrings/attr name. Could you also please add this newly added attribute into our `menu.py` example and also document it in `menu.md`?

2022-10-10 05:34 UTC, mturoci commented on ui/src/menu.tsx
> +  label?: S
Let's call this title instead of label.
```suggestion
  title?: S
```

2022-10-10 05:34 UTC, mturoci commented on ui/src/menu.tsx
> +  /** The card's label. Mutually exclusive with the icon and image */
```suggestion
  /** The text displayed next to the chevron. Mutually exclusive with the icon and image. */
```

2022-10-10 05:34 UTC, mturoci commented on ui/src/menu.tsx
> +  /** The card's icon. Mutually exclusive with the image and label. */
```suggestion
  /** The card's icon. Mutually exclusive with the image and title. */
```

2022-10-10 05:34 UTC, mturoci commented on ui/src/menu.tsx
> +  /** The card’s image, preferably user avatar. Mutually exclusive with the icon and label. */
```suggestion
  /** The card’s image, preferably user avatar. Mutually exclusive with the icon and title. */
```

2022-10-10 05:34 UTC, mturoci commented on ui/src/menu.tsx
> +      {label}
Let's add a bit of styling and themability.

```suggestion
      {title && <Fluent.Text variant='mediumPlus' styles={{ root: { color: cssVar('$text') } }}>{title}</Fluent.Text>}
```

2022-10-10 19:10 UTC, Pooja444 commented
@mturoci thanks for reviewing my PR! I addressed all your review comments, added an example for `title` in `menu.py`, added documented it in `menu.md`. I also ran `make generate` which automatically added `title` in a few other files. Please review and let me know if the updates look good.

I also tested it again after the changes - 

Successful local test -

<img width="798" alt="Screen Shot 2022-10-10 at 12 09 07 PM" src="https://user-images.githubusercontent.com/24620969/194936353-25fced80-9d7f-416f-b590-eb78b027e542.png">


Successful menu.py example run -

<img width="1135" alt="Screen Shot 2022-10-10 at 11 52 38 AM" src="https://user-images.githubusercontent.com/24620969/194936496-bd1a436a-1d56-4854-bf9d-a9e571591420.png">

<img width="1051" alt="Screen Shot 2022-10-10 at 12 09 50 PM" src="https://user-images.githubusercontent.com/24620969/194936529-38f2b942-4b22-4327-b919-c03d4ed8bed2.png">

2022-10-12 07:48 UTC, mturoci submitted a review, later dismissed
Thanks @Pooja444, this is one of the nicest community PRs we received so far! I will label it as `hacktoberfest-accepted`.

@lo5 can you please have a quick look at the API changes? Thanks!

2022-10-14 02:57 UTC, Pooja444 commented
> Looks great @Pooja444! A few minor changes. Also do not forget to run `make generate` after changing the docstrings/attr name. Could you also please add this newly added attribute into our `menu.py` example and also document it in `menu.md`?

Thanks a lot @mturoci !! 😁

2022-10-14 02:57 UTC, Pooja444 commented
> Thanks @Pooja444, this is one of the nicest community PRs we received so far! I will label it as `hacktoberfest-accepted`.
> 
> @lo5 can you please have a quick look at the API changes? Thanks!

Thanks a lot @mturoci !! 😁

2022-11-03 08:33 UTC, merged

2022-11-07 14:33 UTC, Rmfjd1978 commented
This change will be in wich h2o wave version?
bacause i've installed the  0.23.1 and the parameter label is not available on ui.menu

2022-11-07 14:56 UTC, mturoci commented
In the next release - 0.24. Currently available in nightly release.