[DOCS] Conda install
h2oai/wave pull request #1686
Opened 2022-11-04 17:07 UTC by zainhaq-h2o

2022-11-04 17:09 UTC, zainhaq-h2o commented
@mturoci Based on feedback from @Ironsss, I added the line `conda config --append channels conda-forge`.

2022-11-04 17:35 UTC, Ironsss approved these changes

2022-11-04 19:15 UTC, Ironsss requested changes
I suggest the folowing instructions 

conda create -n venv
conda activate venv 
conda config --append channels conda-forge
conda install -c h2oai h2o-wave

2022-11-07 08:53 UTC, mturoci approved these changes

2022-11-07 08:53 UTC, mturoci commented
Thanks @zainhaq-h2o and @Ironsss!

2022-11-07 08:54 UTC, merged