feat: Update custom css docs
h2oai/wave pull request #1723
Opened 2022-11-28 14:33 UTC by marek-mihok

Adds the example of how to apply the css stylesheet stored on the Wave server.

2022-11-28 20:28 UTC, marek-mihok commented
@mturoci now I am reading through your Discord answers regarding this. Maybe it would be fine to also add here a point about css stylesheet served directly from the Wave server. Wdyt?

2022-11-29 08:39 UTC, mturoci requested changes
Thanks @marek-mihok. In addition to these comments, please also add a small comment to `meta_stylesheet.py`'s path. Something like - this path can also be the one returned from q.site.upload if you want to use your own CSS files.

2022-11-29 08:39 UTC, mturoci commented on website/docs/custom-css.md
> +It is also possible to host a stylesheet on the Wave server itself.
Let's add h3 here, something like `### Using local CSS file`.

2022-11-29 08:39 UTC, mturoci commented on website/docs/custom-css.md
> +It is also possible to host a stylesheet on the Wave server itself.
```suggestion
Prior to using your own CSS files, they need to be uploaded to Wave server. There are 2 ways of doing this:

* Uploading the CSS files from your Wave app via [q.site.upload](https://wave.h2o.ai/docs/files/#provide-file-downloads).
* Serving the CSS files directly from Wave server via [public/private dir](https://wave.h2o.ai/docs/files/#serving-files-directly-from-the-wave-server).
```

2022-11-29 08:39 UTC, mturoci commented on website/docs/custom-css.md
> +example_dir = os.path.dirname(os.path.realpath(__file__))
```suggestion
from h2o_wave import Q, main, app, ui
import os

current_dir = os.path.dirname(os.path.realpath(__file__))
```

2022-11-29 08:39 UTC, mturoci commented on website/docs/custom-css.md
> +@app('/demo')
```suggestion
@app('/')
```

2022-11-29 10:54 UTC, mturoci approved these changes

2022-11-29 10:54 UTC, merged