feat: Allow users to remove paddings on frame cards.
h2oai/wave pull request #1735
Opened 2022-12-05 21:57 UTC by kitty3190

Added a parameter called `has_padding` in the `State` interface of `frame.tsx`. Users can specify whether they want the frame cards to have paddings or not. `has_padding` defaults to `true`.

Example:
<img width="886" alt="Screenshot 2022-12-03 at 12 27 29" src="https://user-images.githubusercontent.com/92182939/205453747-7ef26f12-0d4f-43a5-a95b-d263f79d6cdb.png">
<img width="888" alt="Screenshot 2022-12-03 at 12 27 36" src="https://user-images.githubusercontent.com/92182939/205453752-7d4bafc1-4d0a-4131-af89-a725e3b56234.png">

The changes are reflected above. The first frame card with default padding (`has_padding` not specified), the second frame card with padding specified, and the third frame card with no padding specified. 

The code used for testing the changes above:
```py
# Frame card with default padding
page['example1'] = ui.frame_card(
    box='1 1 -1 4',
    title='Frame card with default padding',
    path='https://example.com',
)

# Frame card with padding
page['example2'] = ui.frame_card(
    box='1 5 -1 4',
    title='Frame card with padding specified',
    path='https://example.com',
    has_padding=True
)

# Frame card with no padding
page['example3'] = ui.frame_card(
    box='1 9 -1 4',
    title='Frame card with no padding specified',
    path='https://example.com',
    has_padding=False
)
```
This pull request closes #495.

2022-12-06 14:45 UTC, mturoci requested changes
Thanks @kitty3190!

Based on your screenshots, it seems like it might be a good idea to also not display the title (even if specified) if the padding is turned off. This way, the whole frame card should be occupied purely with the `content` (be it an HTML or 3rd party site link).

Make sure to reflect the above in docstrings as well.

2022-12-06 14:45 UTC, mturoci commented on ui/src/frame.tsx
> +  has_padding?: B
Let's rename it to `compact` to be consistent with the existing API.

2022-12-07 18:02 UTC, kitty3190 commented
Thanks for the review @mturoci! I addressed the issues in my latest commit.

2022-12-08 08:55 UTC, mturoci requested changes
Looking good. I forgot the docs last time. Can you please add this to both `frame.md` files? Once done, it's good to be merged.

2022-12-08 08:55 UTC, mturoci commented on ui/src/frame.tsx
> +      <div data-test={name} className={clas(css.card, (state.compact ?? false) ? '' : css.cardPadding)}>
nit: It's going to be falsy by default anyway so this should be enough.
```suggestion
      <div data-test={name} className={clas(css.card, state.compact ? '' : css.cardPadding)}>
```

2022-12-08 21:52 UTC, kitty3190 commented
Thanks @mturoci! I've added documentation in the `frame.md` file inside the `content` folder which relates to `ui.frame_card` in my latest commit. I believe the other `frame.md` file in the `form` folder relates to `ui.frame` which I did not modify. Let me know if additional changes are required!

2022-12-09 00:31 UTC, lo5 submitted a review, later dismissed

2022-12-09 08:20 UTC, mturoci approved these changes

2022-12-09 08:20 UTC, merged