Wavelite
h2oai/wave pull request #1818
Opened 2023-01-31 16:03 UTC by mturoci

Closes #1796

2023-02-15 16:54 UTC, lo5 requested changes
I'd prefer "Wave Lite" instead of "Wavelite" if that's the name we're going for.
We can also brainstorm other names (lightwave?).

2023-02-15 16:54 UTC, lo5 commented on py/h2o_wavelite/README.md
> +H2O Wavelite is a lighter version of [H2O Wave](https://wave.h2o.ai/) consisting of python driver only, no Golang server. This allows for seamless integration into popular existing python web framewo
```suggestion
H2O Wave Lite is a lightweight, pure-Python version of [H2O Wave](https://wave.h2o.ai/) that can be embedded in popular web frameworks like  Django, Flask, FastAPI, Starlette, etc. 

In other words, H2O Wave Lite works without the Wave server.
```

2023-02-15 16:54 UTC, lo5 commented on py/h2o_wavelite/README.md
> +* Serve Wavelite's static web dir at the route of your choice.
```suggestion
* Add Wave's web assets directory to your framework's static file handler.
```

2023-02-15 16:54 UTC, lo5 commented on py/h2o_wavelite/README.md
> +* Set up a WebSocket connection and hook `wave_serve` callback function to control the UI.
```suggestion
* Add a WebSocket handler, and use `wave_serve()` to connect connect Wave to your web UI.
```

2023-02-15 16:54 UTC, lo5 commented on py/h2o_wavelite/README.md
> +Done. You can render UI elements with nothing but Python. Wavelite aims to be as simplistic as possible and only provides:
```suggestion
That's it. You can now render UI elements using pure Python. Wave Lite aims to be as minimal as possible and only provides:
```

2023-02-15 16:56 UTC, lo5 commented
Overall, great PR. I like how minimal the changes are. 

What about the file upload/download routines from Wave - those won't function properly in the light version, correct?

2023-02-16 10:09 UTC, mturoci commented
>What about the file upload/download routines from Wave - those won't function properly in the light version, correct?

They are not part of the python API at all meaning the type system should take care of it. Will make this clear in the README though.

2023-02-16 10:10 UTC, mturoci commented
>We can also brainstorm other names (lightwave?)

Definitely, created a poll in Slack to get broader ideas. Wavelite was just the first thing that came to my mind, not final for sure.

2023-02-24 11:26 UTC, merged