feat: Allow specifying height for ui.inline #1780
h2oai/wave pull request #1820
Opened 2023-02-01 11:56 UTC by marek-mihok

This change adds the `height` prop for ui.inline component.
```ts
interface Inline {
  /** The components laid out inline. */
  items: Component[]
  /** Specifies how to lay out the individual components. Defaults to 'start'. */
  justify?: 'start' | 'end' | 'center' | 'between' | 'around'
  /** Specifies how the individual components are aligned on the vertical axis. Defaults to 'center'. */
  align?: 'start' | 'end' | 'center' | 'baseline'
  /** Whether to display the components inset from the parent form, with a contrasting background. */
  inset?: B
  /** Custom height  in `px`, `vh` or `rem`. Use '1' to fill the height of the remaining space. E.g. '100vh', '300px' or '1'. */
  height?: S
}
```
As API description says, the accepted values are the following CSS units: `px`, `vh` or `rem`. It is also possible to fill the all remaining height of the parent component by specifying `1`.

Resolves _ui.inline height_ part of the #1780.

2023-02-02 07:48 UTC, mturoci requested changes
Thanks @marek-mihok. Can you also add some useful examples showcasing when can this be helpful to the docs?

2023-02-02 07:48 UTC, mturoci commented on ui/src/form.tsx
> +  /** Custom height  in `px`, `vh` or `rem`. Use '1' to fill the height of the remaining space. E.g. '100vh', '300px' or '1'. */
```suggestion
  /** Height of the inline container. Accepts any valid CSS unit e.g. '100vh', '300px'. Use '1' to fill the remaining card space. */
```

2023-02-02 07:48 UTC, mturoci commented on ui/src/form.tsx
> +      height={/^\d+(\.\d+)?(px|rem|vh)$|^1$/.test(m.height || '') ? m.height : undefined}
This is unnecessary, the docs should be enough.
```suggestion
      height={m.height}
```

2023-02-02 09:34 UTC, marek-mihok commented
@mturoci sure. Also I will add a better example (login page) once the direction is implemented for ui.inline.

2023-02-02 09:51 UTC, mturoci commented
> Also I will add a better example (login page) once the direction is implemented for ui.inline.

It would be better to have examples for both, height-only and height + direction.

2023-02-02 12:53 UTC, mturoci approved these changes
LGTM. @lo5 can you do a quick API review, please? Thanks!

2023-02-06 19:06 UTC, lo5 approved these changes

2023-02-07 07:05 UTC, merged