fix: Disable Select/Deselect all buttons when ui.dropdown is disabled
h2oai/wave pull request #1822
Opened 2023-02-01 15:43 UTC by marek-mihok

Closes #1821

2023-02-01 15:45 UTC, Far0n commented
that was fast :D

2023-02-02 07:02 UTC, mturoci requested changes
Thanks @marek-mihok! One small comment and it's good to go.

2023-02-02 07:02 UTC, mturoci commented on ui/src/dropdown.test.tsx
> +      expect(wave.args[name]).toMatchObject(['A'])
Let's make the initial state clear.
```suggestion
      expect(wave.args[name]).toMatchObject(['A'])

      fireEvent.click(getByText('Select All'))

      expect(wave.args[name]).toMatchObject(['A'])
```

2023-02-02 07:02 UTC, mturoci commented on ui/src/dropdown.test.tsx
> +    it('Do not deselect all options on Deselect all - dropdown disabled', () => {
Same as comment above.

2023-02-02 09:49 UTC, mturoci approved these changes

2023-02-02 09:50 UTC, merged