[DevOps] Snyk Integration
h2oai/wave pull request #1859
Opened 2023-02-28 12:50 UTC by ChathurindaRanasinghe

**Description**

- Fixed deprecation issues with the `set-output` command. - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Changed the organisation to [WAVE](https://app.snyk.io/org/wave)
- Updated GitHub Action versions for Python.
- Updated the [changed-files](https://github.com/marketplace/actions/changed-files) GitHub Action version.
- `remote-repo-url` will follow `repo/branch` format & `project-name` will follow `PRODUCT/repo/branch/file` format.

**Parent Issues**

- https://github.com/h2oai/h2o-ops/issues/285
- https://github.com/h2oai/h2o-ops/issues/241

2023-03-07 04:27 UTC, lo5 submitted a review, later dismissed

2023-03-07 10:13 UTC, mturoci requested changes
Thanks @ChathurindaRanasinghe. Unfortunately, it seems like this PR doesn't solve the problem. I created a new branch off this one and made a new PR to verify this works, but keep getting the same error - https://github.com/h2oai/wave/actions/runs/4352959484/jobs/7606400169.

2023-03-07 10:26 UTC, ChathurindaRanasinghe commented on .github/workflows/snyk-scan.yml
> +          go-version: "1.15"
Sure, I will update the version.

2023-03-07 10:27 UTC, ChathurindaRanasinghe commented
> Thanks @ChathurindaRanasinghe. Unfortunately, it seems like this PR doesn't solve the problem. I created a new branch off this one and made a new PR to verify this works, but keep getting the same error - https://github.com/h2oai/wave/actions/runs/4352959484/jobs/7606400169.

I will add a Snyk policy file to ignore those errors.

2023-03-08 02:06 UTC, ChathurindaRanasinghe commented on .github/workflows/snyk-scan.yml
> +          go-version: "1.15"
done

2023-03-08 02:09 UTC, ChathurindaRanasinghe commented
![image](https://user-images.githubusercontent.com/67860730/223601122-d53b438a-def8-4f17-8d86-ecbf8dc97d89.png)

cc: @mturoci

2023-03-08 07:51 UTC, mturoci approved these changes

2023-03-08 07:52 UTC, merged