fix: Apply primary button styles for icon button #2121
h2oai/wave pull request #2137
Opened 2023-09-13 12:47 UTC by marek-mihok

**The PR fulfills these requirements:** (check all the apply)

- [x] It's submitted to the `main` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [x] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [x] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [ ] New/updated tests are included

___

Closes #2121

2023-09-14 07:01 UTC, mturoci requested changes
Thanks @marek-mihok.

* What's the reason for not using the existing `Fluent.PrimaryButton` instead of mimicking it with custom styles?
* The colors doesn't look good on other themes.
* Make this part of our visual regression testing by including the primary icon button within `md` docs.

2023-09-14 09:47 UTC, marek-mihok commented
> What's the reason for not using the existing Fluent.PrimaryButton instead of mimicking it with custom styles?

@mturoci the primary button with icon only is much wider than icon button (it has horizontal padding)

2023-09-14 10:19 UTC, mturoci commented
I don't understand. That's the point of the issue, isn't it? If `primary=True`, render a primary button. The padding is specific to primary button styles which is desired - so that people understand it's primary.

2023-09-18 09:29 UTC, mturoci approved these changes

2023-09-18 09:29 UTC, merged