fix: Make file upload work when waved run separately #2225
h2oai/wave pull request #2232
Opened 2024-01-09 11:11 UTC by marek-mihok

**The PR fulfills these requirements:** (check all the apply)

- [x] It's submitted to the `main` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [x] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [ ] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [ ] New/updated tests are included

___

This PR fixes the issue when `H2O_WAVE_WAVED_DIR` has a wrong value in [some scenarios](https://github.com/h2oai/wave/issues/2225#issuecomment-1862522354). The fix is accomplished by finding the PID of the `waved/waved.exe` and getting its CWD which is then set to `H2O_WAVE_WAVED_DIR` env variable.

Successfully tested on both Mac and Windows.

Closes #2225

2024-01-09 11:45 UTC, mturoci requested changes
Looking good @marek-mihok! Can we do without external lib though?

2024-01-09 11:45 UTC, mturoci commented on py/h2o_wave/pyproject.toml
> +    "psutil>=5.9.7",
Can this be done without external dep? Seems like this PR is using it for a single function anyway.

2024-01-09 11:45 UTC, mturoci commented on py/h2o_wave/h2o_wave/cli.py
> +            os.environ['H2O_WAVE_WAVED_DIR'] = waved_cwd
If this works reliably, we can deprecate `H2O_WAVE_WAVED_DIR`. Add a TODO here for now.

2024-01-09 11:45 UTC, mturoci commented on py/h2o_wave/h2o_wave/cli.py
> +    waved_path = os.path.join(waved_cwd, proc_name)
This is only true for platform specific wheel files. Platform-agnostic whl does not contain waved binary.

2024-01-16 17:20 UTC, marek-mihok commented
> Can we do without external lib though?

@mturoci my research shows there is no pythonic (or other simple) way of getting process cwd by its name on Windows. Libs like `psutil` or `win32com` use complex solutions for this simple problem.

Maybe we could include `psutil` as the os specific dependency? For Windows only? And use external lib free solution otherwise?

2024-01-17 06:43 UTC, mturoci commented
> there is no pythonic (or other simple) way of getting process cwd by its name on Windows

In that case, you can either implement for UNIX systems only and defer to HTTP on err and Windows or go for HTTP everywhere and keep using `H2O_WAVE_WAVED_DIR` for speedup if needed.

2024-01-18 13:34 UTC, mturoci commented
Added a small refactor. @marek-mihok please verify if works. If it does, good to merge. Thanks!

2024-01-22 14:39 UTC, marek-mihok commented
@mturoci works, it's good to go.

2024-01-23 09:22 UTC, merged