feat: Prompt suggestions for ui.chatbot #2250
h2oai/wave pull request #2265
Opened 2024-02-12 21:26 UTC by marek-mihok

**The PR fulfills these requirements:** (check all the apply)

- [x] It's submitted to the `main` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [x] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [ ] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [ ] New/updated tests are included

___

This PR brings `prompt_suggestions: ChatPromptSuggestion[]` attribute to show clickable prompt suggestions under the last response in ui.chatbot component. When the suggestion is clicked, it fires `prompt_suggestion` event which can subsequently be handled by the user.

The user input can be limited to prompt suggestions only by specifying `disabled` prop which disables user input or it can be used in a combination with text input as well.

https://github.com/h2oai/wave/assets/23740173/707c74a9-0508-4cc3-aba8-4e73549758f2

Updated API is as follows:
```tsx
/** Create a chat prompt suggestion displayed as button below the last response in chatbot component. */
export interface ChatPromptSuggestion {
  /** An identifying name for this component. */
  name: Id
  /** The text displayed for this suggestion. */
  label: S
}

/** Create a chatbot card to allow getting prompts from users and providing them with LLM generated answers. */
export interface Chatbot {
  /** An identifying name for this component. */
  name: Id
  /** Chat messages data. Requires list or cyclic buffer. */
  data: Rec
  /** Chat input box placeholder. Use for prompt examples. */
  placeholder?: S
  /** The events to capture on this chatbot. One of 'stop' | 'scroll_up' | 'feedback' | 'prompt_suggestion'. */
  events?: S[]
  /** True to show a button to stop the text generation. Defaults to False. */
  generating?: B
  /** The previous messages to show as the user scrolls up. */
  prev_items?: ChatbotMessage[]
  /** Clickable prompt suggestions shown below the last response. */
  prompt_suggestions?: ChatPromptSuggestion[]
  /** True if the user input should be disabled. */
  disabled?: B
}
```

The same API update also applies to `ui.chatbot_card` component.

Closes #2250

2024-02-14 13:22 UTC, marek-mihok commented
First 2 points are done:

- Initial "head start" suggestions with captions and icons

https://github.com/h2oai/wave/assets/23740173/feabd35c-41c3-40d6-9fd3-781e1860b749

- Prompt "in-chat" suggestions

https://github.com/h2oai/wave/assets/23740173/826238cb-bd9a-4fd6-a598-ea20212b885f


> The example could use some polish as well, it's very rough at the moment.

@mturoci what do you mean by rough? In terms of code quality or the use case relevance? Can you give me some thoughts about what you consider a proper example?

2024-02-14 13:45 UTC, mturoci commented
> what do you mean by rough?

Would that demo persuade you to use Wave? Probably not. Would be better to append the suggestion right away, but add a slight timeout on suggestion selection to emulate computation, hide suggestions in the meantime, then append the response.

2024-02-14 13:46 UTC, mturoci commented
> First 2 points are done:

Looks better, the border radius is off though. Try to use the same as used in the rest of our cards/components.

2024-02-16 09:27 UTC, mturoci requested changes
Looks good, just a few small comments.

2024-02-16 09:27 UTC, mturoci commented on ui/src/chatbot.tsx
> +    hasSomeCaption = React.useMemo(() => props.prompt_suggestions?.some(({ caption }) => !!caption), [props.prompt_suggestions]),
No need for memo here. We expect a few suggestions only so safe to recompute on every render.

2024-02-16 09:27 UTC, mturoci commented on ui/src/chatbot.tsx
> +        {props.prompt_suggestions && props.prompt_suggestions.length > 0 &&
nit

```suggestion
        {!!props.prompt_suggestions?.length &&
```

2024-02-16 09:27 UTC, mturoci commented on website/docs/examples/assets/chatbot-events-suggestions.png
Update.

2024-02-16 09:27 UTC, mturoci commented on ui/src/chatbot.tsx
> +  prompt_suggestions?: ChatPromptSuggestion[]
```suggestion
  suggestions?: ChatSuggestion[]
```

2024-02-16 14:19 UTC, mturoci approved these changes

2024-02-16 14:19 UTC, merged