Added enter handler for textbox #372
h2oai/wave pull request #2355
Opened 2024-06-21 19:08 UTC by haneenabdo

Closes #372 
**The PR fulfills these requirements:** (check all the apply)

- [x] It's submitted to the `main` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [x] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [x] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [x] New/updated tests are included

2024-06-24 11:42 UTC, mturoci requested changes
Thanks @haneenabdo! Can you pleases also include unit tests and a video demo of how your changes work in practice?

2024-06-24 11:42 UTC, mturoci commented on ide/tsconfig.json
> +		"include": ["src", "node_modules/@types"],
Why is this needed?

2024-06-24 11:42 UTC, mturoci commented on ui/src/textbox.tsx
> +  onEnter?: B
We should probably do this by default, no need for an extra prop.

2024-06-28 16:14 UTC, michaeltraxler commented
I would be really happy if this PR would be committed, as I also really need the feature, that pressing Enter in a textbox will call the handler (do something with the contents). An additional button just for this is really not what the people will expect and slow in our environment.

2024-08-06 07:19 UTC, mturoci commented
Closing as inactive.

2024-08-06 07:19 UTC, closed without merging

2025-03-29 09:52 UTC, Sachin-Ram commented
is this issue still active?