feat: Add ML API as a pip option
h2oai/wave pull request #532
Opened 2021-01-28 16:19 UTC by geomodular

If PR merged, the first version of ML API will be available in Wave. ML API is completely separated and will be installable by:
```sh
pip install h2o-wave[ml]
```

2021-01-28 19:11 UTC, Sassybabydoll1969 approved these changes

2021-01-28 19:40 UTC, Sassybabydoll1969 approved these changes

2021-01-28 19:41 UTC, Sassybabydoll1969 submitted a review, later dismissed

2021-02-04 17:48 UTC, lo5 requested changes
Thanks @geomodular - we can merge when this can pull from pypi instead of github.

2021-02-08 16:27 UTC, lo5 approved these changes

2021-02-08 16:27 UTC, merged