test: Testcases for Submit command value when clicked, if available
h2oai/wave pull request #662
Opened 2021-03-23 17:38 UTC by VijithaEkanayake

testcases for https://github.com/h2oai/wave/issues/661

2021-03-26 08:52 UTC, mturoci requested changes
Thanks @VijithaEkanayake. A few comments. Please also include tests for case when value starts with a hash.

2021-03-26 08:52 UTC, mturoci commented on ui/src/toolbar.test.tsx
> +  commandLabel = commandName,
Not needed as it is the name.

2021-03-26 08:52 UTC, mturoci commented on ui/src/toolbar.test.tsx
>    }
No need for these, use existing `toolbarProps` with base state: ` state: { items: [{ name: commandName, label: commandLabel }] },` and add value within specific test case as needed. Be careful to not change the original base props instance for further tests.

2021-03-26 08:52 UTC, mturoci commented on ui/src/toolbar.test.tsx
> +  it('Sets args and calls sync on click - with value attr', () => {
missing check if sync was called

2021-03-26 08:52 UTC, mturoci commented on ui/src/toolbar.test.tsx
> +  it('Sets args and calls sync on click - without value attr', () => {
missing check if sync was called

2021-03-31 05:27 UTC, VijithaEkanayake commented
> Thanks @VijithaEkanayake. A few comments. Please also include tests for cases when the value starts with a hash.

@mturoci All the suggestions are introduced. Kindly have a look.

2021-03-31 06:48 UTC, VijithaEkanayake commented
@mturoci  Please refer to PR: https://github.com/h2oai/wave/pull/717 which introduces the requested changes. I don't seem to have the permissions to request a review from anyone it just default reviewer.

2021-03-31 06:48 UTC, closed without merging