feat: Make closable dialog emit event on close #790
h2oai/wave pull request #813
Opened 2021-05-13 08:03 UTC by mturoci

Closes #790

2021-05-14 01:57 UTC, lo5 requested changes

2021-05-14 01:57 UTC, lo5 commented on ui/src/dialog.tsx
> +      if (closable && name) {
Raise event only if subscribed.

2021-05-14 01:57 UTC, lo5 commented
Additionally, needs a screenshot for the new example.

2021-05-14 09:53 UTC, mturoci commented on ui/src/dialog.tsx
> +  name?: Id
Done.

2021-05-14 09:54 UTC, mturoci commented on ui/src/dialog.tsx
> +      if (closable && name) {
Done.

2021-05-14 09:54 UTC, mturoci commented on py/examples/meta_dialog_closable.py
> +        q.page['meta'].dialog = ui.dialog(title='Order Donuts', name='dialog', closable=True, items=[
Done.

2021-05-19 16:50 UTC, lo5 submitted a review, later dismissed

2021-05-19 16:53 UTC, lo5 approved these changes

2021-05-19 16:53 UTC, merged