feat: Custom inline / external CSS support. #965
h2oai/wave pull request #973
Opened 2021-08-19 11:47 UTC by mturoci

Closes #965

2021-08-19 16:05 UTC, lo5 requested changes
Minor changes to API. Thanks @mturoci!

2021-08-19 16:05 UTC, lo5 commented on ui/src/meta.tsx
> +  style?: S
```suggestion
  stylesheet?: InlineStylesheet
```

`InlineStylesheet` (consistent with InlineScript) can contain `content` and `media?` (for consistency with `Stylesheet.media`).

2021-08-19 16:05 UTC, lo5 commented on ui/src/meta.tsx
> +  styles?: Style[]
```suggestion
  stylesheets?: Stylesheet[]
```

2021-08-19 16:05 UTC, lo5 commented on ui/src/meta.tsx
> +  /** CSS to be inlined into this page. */
```suggestion
  /** CSS stylesheet to be applied to this page. */
```

2021-08-20 07:36 UTC, mturoci commented
Thanks for the review @lo5! Comments addressed.

2021-08-25 15:30 UTC, merged